In [1]:
# Numpy - Array Manipulation

In [2]:
import numpy as np

In [3]:
arr = np.random.randint(1,10,(3,4))

In [4]:
arr

array([[4, 8, 9, 6],
       [2, 8, 8, 7],
       [1, 6, 3, 7]])

In [5]:
arr.reshape(6,2)

array([[4, 8],
       [9, 6],
       [2, 8],
       [8, 7],
       [1, 6],
       [3, 7]])

In [6]:
arr.reshape(2,6)

array([[4, 8, 9, 6, 2, 8],
       [8, 7, 1, 6, 3, 7]])

In [7]:
arr.reshape(2,4762)

ValueError: cannot reshape array of size 12 into shape (2,4762)

In [8]:
arr.reshape(2,-28658623)

array([[4, 8, 9, 6, 2, 8],
       [8, 7, 1, 6, 3, 7]])

In [9]:
arr.T

array([[4, 2, 1],
       [8, 8, 6],
       [9, 8, 3],
       [6, 7, 7]])

In [10]:
arr

array([[4, 8, 9, 6],
       [2, 8, 8, 7],
       [1, 6, 3, 7]])

In [11]:
arr.ndim

2

In [12]:
arr.flatten()

array([4, 8, 9, 6, 2, 8, 8, 7, 1, 6, 3, 7])

In [15]:
arr1 = np.array([1,2,3,3,4])

In [16]:
arr1

array([1, 2, 3, 3, 4])

In [17]:
arr1.ndim

1

In [18]:
np.expand_dims(arr1, axis = 1)

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [19]:
np.expand_dims(arr1, axis = 0)

array([[1, 2, 3, 3, 4]])

In [20]:
arr

array([[4, 8, 9, 6],
       [2, 8, 8, 7],
       [1, 6, 3, 7]])

In [21]:
np.squeeze(arr)

array([[4, 8, 9, 6],
       [2, 8, 8, 7],
       [1, 6, 3, 7]])

In [22]:
data = np.array([[1] , [2] , [3]])

In [23]:
data

array([[1],
       [2],
       [3]])

In [24]:
np.squeeze(data)

array([1, 2, 3])

In [25]:
arr1

array([1, 2, 3, 3, 4])

In [26]:
np.repeat(arr1,3)  # (array, number of repetation)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [28]:
np.roll(arr1 , 2)

array([3, 4, 1, 2, 3])

In [29]:
arr1

array([1, 2, 3, 3, 4])

In [30]:
np.roll(arr1 , 1)

array([4, 1, 2, 3, 3])

In [31]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [32]:
# Numpy - Binary Operations.

In [35]:
arr1 = np.random.randint(1,10,(3,4))
arr2 = np.random.randint(1,10,(3,4))

In [45]:
arr1

array([[1, 9, 2, 3],
       [7, 6, 3, 4],
       [2, 1, 8, 5]])

In [46]:
arr2

array([[4, 5, 1, 4],
       [8, 7, 7, 6],
       [9, 5, 2, 3]])

In [47]:
arr1+arr2

array([[ 5, 14,  3,  7],
       [15, 13, 10, 10],
       [11,  6, 10,  8]])

In [48]:
arr1*arr2

array([[ 4, 45,  2, 12],
       [56, 42, 21, 24],
       [18,  5, 16, 15]])

In [49]:
arr1/arr2

array([[0.25      , 1.8       , 2.        , 0.75      ],
       [0.875     , 0.85714286, 0.42857143, 0.66666667],
       [0.22222222, 0.2       , 4.        , 1.66666667]])

In [50]:
arr1-arr2

array([[-3,  4,  1, -1],
       [-1, -1, -4, -2],
       [-7, -4,  6,  2]])

In [51]:
arr1%arr2

array([[1, 4, 0, 3],
       [7, 6, 3, 4],
       [2, 1, 0, 2]])

In [52]:
arr1**arr2

array([[      1,   59049,       2,      81],
       [5764801,  279936,    2187,    4096],
       [    512,       1,      64,     125]])

In [53]:
arr1 & arr2

array([[0, 1, 0, 0],
       [0, 6, 3, 4],
       [0, 1, 0, 1]])

In [54]:
arr1

array([[1, 9, 2, 3],
       [7, 6, 3, 4],
       [2, 1, 8, 5]])

In [55]:
arr2

array([[4, 5, 1, 4],
       [8, 7, 7, 6],
       [9, 5, 2, 3]])

In [56]:
~arr1

array([[ -2, -10,  -3,  -4],
       [ -8,  -7,  -4,  -5],
       [ -3,  -2,  -9,  -6]])

In [57]:
arr1|arr2

array([[ 5, 13,  3,  7],
       [15,  7,  7,  6],
       [11,  5, 10,  7]])

In [58]:
arr1>arr2

array([[False,  True,  True, False],
       [False, False, False, False],
       [False, False,  True,  True]])

In [59]:
# Numpy - String Functions.

In [61]:
arr = np.array(['Dushyant', 'Kumar'])

In [62]:
arr

array(['Dushyant', 'Kumar'], dtype='<U8')

In [63]:
np.char.upper(arr)

array(['DUSHYANT', 'KUMAR'], dtype='<U8')

In [64]:
np.char.title(arr)

array(['Dushyant', 'Kumar'], dtype='<U8')

In [65]:
np.char.capitalize(arr)

array(['Dushyant', 'Kumar'], dtype='<U8')

In [73]:
# Numpy - Mathmatical Functions.

In [74]:
arr1

array([[1, 9, 2, 3],
       [7, 6, 3, 4],
       [2, 1, 8, 5]])

In [76]:
np.sin(arr1)

array([[ 0.84147098,  0.41211849,  0.90929743,  0.14112001],
       [ 0.6569866 , -0.2794155 ,  0.14112001, -0.7568025 ],
       [ 0.90929743,  0.84147098,  0.98935825, -0.95892427]])

In [77]:
np.cos(arr1)

array([[ 0.54030231, -0.91113026, -0.41614684, -0.9899925 ],
       [ 0.75390225,  0.96017029, -0.9899925 , -0.65364362],
       [-0.41614684,  0.54030231, -0.14550003,  0.28366219]])

In [78]:
np.tan(arr1)

array([[ 1.55740772, -0.45231566, -2.18503986, -0.14254654],
       [ 0.87144798, -0.29100619, -0.14254654,  1.15782128],
       [-2.18503986,  1.55740772, -6.79971146, -3.38051501]])

In [79]:
np.sinh(arr1)

array([[1.17520119e+00, 4.05154190e+03, 3.62686041e+00, 1.00178749e+01],
       [5.48316123e+02, 2.01713157e+02, 1.00178749e+01, 2.72899172e+01],
       [3.62686041e+00, 1.17520119e+00, 1.49047883e+03, 7.42032106e+01]])

In [80]:
np.tanh(arr1)

array([[0.76159416, 0.99999997, 0.96402758, 0.99505475],
       [0.99999834, 0.99998771, 0.99505475, 0.9993293 ],
       [0.96402758, 0.76159416, 0.99999977, 0.9999092 ]])

In [81]:
np.log10(arr1)

array([[0.        , 0.95424251, 0.30103   , 0.47712125],
       [0.84509804, 0.77815125, 0.47712125, 0.60205999],
       [0.30103   , 0.        , 0.90308999, 0.69897   ]])

In [82]:
np.exp(arr1)

array([[2.71828183e+00, 8.10308393e+03, 7.38905610e+00, 2.00855369e+01],
       [1.09663316e+03, 4.03428793e+02, 2.00855369e+01, 5.45981500e+01],
       [7.38905610e+00, 2.71828183e+00, 2.98095799e+03, 1.48413159e+02]])

In [83]:
np.sqrt(arr1)

array([[1.        , 3.        , 1.41421356, 1.73205081],
       [2.64575131, 2.44948974, 1.73205081, 2.        ],
       [1.41421356, 1.        , 2.82842712, 2.23606798]])

In [84]:
np.power(arr1,2)

array([[ 1, 81,  4,  9],
       [49, 36,  9, 16],
       [ 4,  1, 64, 25]])

In [85]:
np.mean(arr1)

4.25

In [88]:
np.median(arr1)

3.5

In [89]:
np.std(arr1)

2.6180463454008347

In [90]:
np.var(arr1)

6.854166666666667

In [91]:
np.min(arr1)

1

In [92]:
np.max(arr1)

9