In [2]:
# Sort, Search & Counting Functions.

In [3]:
import numpy as np

In [4]:
arr = np.array([4,3,4,5,6,72,3,3,455,5,6,6])

In [5]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [6]:
np.sort(arr)

array([  3,   3,   3,   4,   4,   5,   5,   6,   6,   6,  72, 455])

In [7]:
np.searchsorted(arr, 34)

12

In [8]:
arr1 = np.array([0,345,453,0,0,0,0,0])

In [9]:
np.count_nonzero(arr1)

2

In [10]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [11]:
np.where(arr>6)

(array([5, 8]),)

In [12]:
np.extract(arr > 3,arr)

array([  4,   4,   5,   6,  72, 455,   5,   6,   6])

In [13]:
# Numpy - Byt Swapping

In [14]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [15]:
arr.byteswap()

array([  288230376151711744,   216172782113783808,   288230376151711744,
         360287970189639680,   432345564227567616,  5188146770730811392,
         216172782113783808,   216172782113783808, -4107001385185181696,
         360287970189639680,   432345564227567616,   432345564227567616])

In [16]:
# Numpy - Copies & Views

In [17]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [18]:
a = np.copy(arr)

In [19]:
a

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [20]:
b = arr.view()

In [21]:
b

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [22]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [23]:
b[0] = 67

In [24]:
b

array([ 67,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [25]:
arr

array([ 67,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [26]:
# Numpy - Matrix Library

In [27]:
import numpy.matlib as nm

In [28]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [29]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [30]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [31]:
# Numpy - Linear Algebra

In [32]:
arr1 = np.random.randint([[2,3], [4,5]])
arr2 = np.random.randint([[2,3], [4,5]])

In [34]:
arr1

array([[0, 1],
       [0, 2]])

In [35]:
arr2

array([[1, 0],
       [0, 2]])

In [33]:
np.dot(arr1,arr2)

array([[0, 2],
       [0, 4]])

In [36]:
arr1@arr2

array([[0, 2],
       [0, 4]])