In [3]:
import numpy as np

In [4]:
# 1D array
a = np.array([1,2,3,4])

In [5]:
type(a)

numpy.ndarray

In [6]:
# 2D array
b = np.array([[1,2,3,4],[2,3,4,5]])

In [7]:
b

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [8]:
type(b)

numpy.ndarray

In [9]:
# 3D array
c = np.array([[[1,2],[23,34]]])

In [10]:
c

array([[[ 1,  2],
        [23, 34]]])

In [11]:
#  dtype
np.array([2,3,4,5],dtype = float)

array([2., 3., 4., 5.])

In [12]:
#  dtype
np.array([2,3,4,5],dtype = bool)

array([ True,  True,  True,  True])

In [13]:
#  dtype
np.array([2,3,4,5],dtype = complex)

array([2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

In [14]:
# np.arange
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [16]:
# with reshape

np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [17]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [18]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
# np.random
np.random.random((3,4))

array([[0.92991942, 0.62877677, 0.55913215, 0.25731586],
       [0.25224042, 0.81622506, 0.29976405, 0.86452711],
       [0.85303688, 0.50069703, 0.85954391, 0.49406474]])

In [22]:
# np.linspace
np.linspace(1,10,56)

array([ 1.        ,  1.16363636,  1.32727273,  1.49090909,  1.65454545,
        1.81818182,  1.98181818,  2.14545455,  2.30909091,  2.47272727,
        2.63636364,  2.8       ,  2.96363636,  3.12727273,  3.29090909,
        3.45454545,  3.61818182,  3.78181818,  3.94545455,  4.10909091,
        4.27272727,  4.43636364,  4.6       ,  4.76363636,  4.92727273,
        5.09090909,  5.25454545,  5.41818182,  5.58181818,  5.74545455,
        5.90909091,  6.07272727,  6.23636364,  6.4       ,  6.56363636,
        6.72727273,  6.89090909,  7.05454545,  7.21818182,  7.38181818,
        7.54545455,  7.70909091,  7.87272727,  8.03636364,  8.2       ,
        8.36363636,  8.52727273,  8.69090909,  8.85454545,  9.01818182,
        9.18181818,  9.34545455,  9.50909091,  9.67272727,  9.83636364,
       10.        ])

In [23]:
# np.indentity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.identity(5,dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

# Array Attributes

In [25]:
a1 = np.arange(10)
a2 = np.arange(12,dtype = float).reshape(3,4)
a3 = np.arange(60).reshape(4,5,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]],

       [[30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]],

       [[45, 46, 47],
        [48, 49, 50],
        [51, 52, 53],
        [54, 55, 56],
        [57, 58, 59]]])

In [26]:
# ndim
a3.ndim

3

In [27]:
# shape
print(a3.shape)
a3

(4, 5, 3)


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]],

       [[30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]],

       [[45, 46, 47],
        [48, 49, 50],
        [51, 52, 53],
        [54, 55, 56],
        [57, 58, 59]]])

In [28]:
#  size
print(a2.size)
print(a3.size)

12
60


In [29]:
#  itemsize
a3.itemsize

8

In [30]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


# Changing Datatype

In [31]:
# astype
a3.astype(np.int32)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]],

       [[30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]],

       [[45, 46, 47],
        [48, 49, 50],
        [51, 52, 53],
        [54, 55, 56],
        [57, 58, 59]]], dtype=int32)

# Array Operations

In [32]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [33]:
# Vector and arithmetic Operation
print(a1+a2)
print()
print(a1*a2)
print()
print(a1-a2)
print()
print(a1/a2)
print()
print(a1*2)
print()
print(a1**2)

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]

[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]

[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]

[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]]

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [34]:
# relational
print(a2 > 5)
print(a2 > 15)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [35]:
# Array Functions
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[80., 16., 37.],
       [10., 30., 60.],
       [64., 74.,  4.]])

In [36]:
# max,min,sum,product
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.product(a1))
print(np.max(a1,axis = 1))
print(np.max(a1,axis = 0))
print(np.min(a1,axis = 1))

80.0
4.0
375.0
16149381120000.0
[80. 60. 74.]
[80. 74. 60.]
[16. 10.  4.]


In [37]:
# mean,median,std,var
print(np.mean(a1,axis = 0))
print(np.median(a1))
print(np.std(a1))
print(np.var(a1))

[51.33333333 40.         33.66666667]
37.0
27.055498516937366
732.0


In [38]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [39]:
# log and exponential
print(a2)
a4 = np.log(a2)
print(a4)
a5 = np.exp(a4)
print(a5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[      -inf 0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947 1.94591015]
 [2.07944154 2.19722458 2.30258509 2.39789527]]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


/tmp/ipykernel_77/4145235561.py:3: RuntimeWarning: divide by zero encountered in log
  a4 = np.log(a2)


In [40]:
#  round,floor,ceil
print(np.round(np.random.random((2,3))*100))
print(np.floor(np.random.random((2,3))*100))

[[33.  5. 80.]
 [58. 85. 35.]]
[[31. 59. 50.]
 [70.  3. 38.]]


In [41]:
# Indexing and Slicing
a1 =  np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)


In [42]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
a1[0]

0

In [44]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
a2[1,2]

6

In [46]:
a2[1,0]

4

In [47]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [48]:
a3[1][0][1]

5

In [49]:
a3[0][1][1]

3

In [50]:
a3[1,1,0]

6

In [51]:
a1[1:4]

array([1, 2, 3])

In [52]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
a1[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [54]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
a2[0,:]

array([0, 1, 2, 3])

In [56]:
a2[:,0]

array([0, 4, 8])

In [57]:
a2[:,1]

array([1, 5, 9])

In [58]:
a2[1,:]

array([4, 5, 6, 7])

In [59]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [60]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [61]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [62]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [63]:
a2[1::2,0::3]

array([[4, 7]])

In [64]:
a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [65]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [66]:
a3 = np.arange(27).reshape(3,3,3)

In [67]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [68]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [69]:
a3[2]

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [70]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [71]:
a3[0,1]

array([3, 4, 5])

In [72]:
a3[1,:,1]

array([10, 13, 16])

In [73]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [74]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [75]:
a3[0::2,0::3,::2]

array([[[ 0,  2]],

       [[18, 20]]])

# Iterating

In [80]:
a1
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [81]:
a2
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [83]:
a3
for i in a3:
    print(i)
    print()

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]

[[18 19 20]
 [21 22 23]
 [24 25 26]]



In [84]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping

In [89]:
# Transpose
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [90]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [88]:
# Ravel
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [92]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [94]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# Stacking

In [96]:
# Horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5  = np.arange(12,24).reshape(3,4)

In [97]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [98]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [99]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [100]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Spliting

In [101]:
# horizonal spliling
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [102]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [105]:
# Vertical Spliting
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [108]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]