In [1]:
import numpy as np

In [2]:
l = [1,2,3,4]

In [4]:
ar = np.array(l)

In [5]:
ar

array([1, 2, 3, 4])

In [6]:
type(ar)

numpy.ndarray

In [7]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [10]:
ar1 = np.asarray(l)

In [11]:
type(ar1)

numpy.ndarray

In [12]:
a = [2,3,4]

In [13]:
np.asanyarray(a)

array([2, 3, 4])

In [14]:
b = np.matrix(l)

In [15]:
b

matrix([[1, 2, 3, 4]])

In [16]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [17]:
a = np.array(l)

In [18]:
a

array([1, 2, 3, 4])

In [19]:
c = a

In [20]:
c

array([1, 2, 3, 4])

In [22]:
c[0] = 100

In [23]:
c

array([100,   2,   3,   4])

In [24]:
a

array([100,   2,   3,   4])

In [25]:
d = np.copy(a)

In [26]:
d

array([100,   2,   3,   4])

In [27]:
a

array([100,   2,   3,   4])

In [28]:
a[1] = 400

In [29]:
a

array([100, 400,   3,   4])

In [30]:
d

array([100,   2,   3,   4])

In [35]:
np.fromfunction(lambda i,j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [36]:
np.fromfunction(lambda i,j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [39]:
iterable = (i*i for i in range(5))

In [41]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [42]:
np.fromstring('234 234', sep = ' ')

array([234., 234.])

In [43]:
np.fromstring('1,2,3,4,5', sep = ',')

array([1., 2., 3., 4., 5.])

In [44]:
 # Numpy - Data Types

In [45]:
l = [2,3,4,5,6]

In [46]:
ar = np.array(l)

In [47]:
ar

array([2, 3, 4, 5, 6])

In [48]:
ar.ndim

1

In [49]:
ar2 = np.array([[1,2,3,4],[2,3,4,5]])

In [50]:
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [51]:
ar2.ndim

2

In [53]:
ar.size

5

In [54]:
ar2.size

8

In [55]:
ar.shape

(5,)

In [56]:
ar2.shapee

(2, 4)

In [58]:
ar.dtype

dtype('int64')

In [59]:
ar2.dtype

dtype('int64')

In [60]:
ar22 = np.array([(1.4,45,45), (23,45,66)])

In [61]:
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [62]:
ar22.dtype

dtype('float64')

In [64]:
list(range(5))

[1, 2, 3, 4]

In [65]:
list(range(0.1,5))

TypeError: 'float' object cannot be interpreted as an integer

In [66]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [67]:
np.arange(2.3,5.6,0.1) #(starting point, end point, jump point)

array([2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5])

In [68]:
list(np.arange(2.3,5.6,0.1))

[2.3,
 2.4,
 2.5,
 2.6,
 2.7,
 2.8000000000000003,
 2.9000000000000004,
 3.0000000000000004,
 3.1000000000000005,
 3.2000000000000006,
 3.3000000000000007,
 3.400000000000001,
 3.500000000000001,
 3.600000000000001,
 3.700000000000001,
 3.800000000000001,
 3.9000000000000012,
 4.000000000000002,
 4.100000000000001,
 4.200000000000001,
 4.300000000000002,
 4.400000000000002,
 4.500000000000002,
 4.600000000000001,
 4.700000000000002,
 4.8000000000000025,
 4.900000000000002,
 5.000000000000002,
 5.100000000000002,
 5.200000000000003,
 5.3000000000000025,
 5.400000000000002,
 5.500000000000003]

In [70]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [71]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [72]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [73]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [74]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [78]:
np.zeros((2,4,2))  # (number of matrix of 4x2)

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [80]:
ar4 = np.zeros((3,4,2,3))

In [81]:
ar4

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [82]:
ar4.ndim

4

In [83]:
np.ones(4)

array([1., 1., 1., 1.])

In [84]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [86]:
on = np.ones((2,3,2))

In [87]:
on

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [88]:
on+5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [89]:
on*4

array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [90]:
np.empty((3,5))

array([[4.66433352e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000]])

In [91]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [92]:
np.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [94]:
np.logspace(2,5,10, base = 2) # (starting number , end number , number of points , base(by default base = 10))

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [98]:
arr = np.random.randn(3,4) # mean = 0 and std = 1

In [99]:
import pandas as pd

In [100]:
pd.DataFrame(arr)

0         1         2         3
0  1.280220  1.023355 -0.258049 -1.187899
1  0.638043 -0.974252 -0.562443 -1.525932
2 -0.802429  0.318518  0.820989 -0.465633

In [101]:
np.random.rand(3,4)

array([[0.07801015, 0.90811948, 0.02674386, 0.9904638 ],
       [0.90110002, 0.34945118, 0.83095346, 0.51284133],
       [0.13765729, 0.21137092, 0.07595765, 0.90619127]])

In [103]:
np.random.randint(1,110,(3,4))

array([[107,  12,  68,  71],
       [ 45,  36,  85,  38],
       [ 19,   6,  68,  58]])

In [105]:
np.random.randint(1,110,(300,400))

array([[ 46, 102,  61, ...,  98, 105,  19],
       [ 14, 101,  13, ...,  64,  13,  39],
       [ 39,  80,  88, ...,  19,  16,  21],
       ...,
       [105,  40,  95, ...,  67,  98,  45],
       [ 16,  75,  63, ...,  43,  31,  64],
       [ 56,  62,  89, ...,  26,  31,  87]])

In [107]:
pd.DataFrame(np.random.randint(1,110,(300,400))).to_csv('test.csv')

In [110]:
arr1 = np.random.rand(3,4) 

In [111]:
arr1

array([[0.87335556, 0.01420035, 0.65425108, 0.2857332 ],
       [0.3071576 , 0.00535125, 0.57494343, 0.79878499],
       [0.1365873 , 0.33526255, 0.01581773, 0.36973326]])

In [114]:
arr2 = arr1.reshape(6,2)

In [115]:
arr2

array([[0.87335556, 0.01420035],
       [0.65425108, 0.2857332 ],
       [0.3071576 , 0.00535125],
       [0.57494343, 0.79878499],
       [0.1365873 , 0.33526255],
       [0.01581773, 0.36973326]])

In [118]:
arr2[1][1]

0.285733202830564

In [121]:
arr2[2:5,1]

array([0.00535125, 0.79878499, 0.33526255])

In [123]:
arr3 = np.random.randint(1,100,(5,5))

In [124]:
arr3

array([[15, 68,  8, 62, 58],
       [46, 25, 31, 74, 72],
       [25,  1, 67, 59,  8],
       [ 4, 63, 37, 47, 15],
       [32, 41, 76, 43, 76]])

In [127]:
arr3[arr3>50]

array([68, 62, 58, 74, 72, 67, 59, 63, 76, 76])

In [128]:
arr3

array([[15, 68,  8, 62, 58],
       [46, 25, 31, 74, 72],
       [25,  1, 67, 59,  8],
       [ 4, 63, 37, 47, 15],
       [32, 41, 76, 43, 76]])

In [130]:
arr3[2:4,[1,2]]

array([[ 1, 67],
       [63, 37]])

In [132]:
arr3[0][0] = 5000

In [133]:
arr3

array([[5000,   68,    8,   62,   58],
       [  46,   25,   31,   74,   72],
       [  25,    1,   67,   59,    8],
       [   4,   63,   37,   47,   15],
       [  32,   41,   76,   43,   76]])

In [135]:
arr4 = np.random.randint(1,3,(3,3))
arr5 = np.random.randint(1,3,(3,3))

In [136]:
arr4

array([[2, 2, 1],
       [1, 1, 2],
       [2, 1, 1]])

In [137]:
arr5

array([[2, 2, 2],
       [1, 2, 2],
       [1, 1, 1]])

In [138]:
arr4+arr5

array([[4, 4, 3],
       [2, 3, 4],
       [3, 2, 2]])

In [139]:
arr4*arr5

array([[4, 4, 2],
       [1, 2, 4],
       [2, 1, 1]])

In [140]:
arr4-arr5

array([[ 0,  0, -1],
       [ 0, -1,  0],
       [ 1,  0,  0]])

In [141]:
arr4/arr5

array([[1. , 1. , 0.5],
       [1. , 0.5, 1. ],
       [2. , 1. , 1. ]])

In [142]:
arr4@arr5  # @ is doint matrix multiplication

array([[7, 9, 9],
       [5, 6, 6],
       [6, 7, 7]])

In [143]:
arr4/0

/tmp/ipykernel_147/1674986024.py:1: RuntimeWarning: divide by zero encountered in divide
  arr4/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [144]:
arr4

array([[2, 2, 1],
       [1, 1, 2],
       [2, 1, 1]])

In [145]:
arr4+100

array([[102, 102, 101],
       [101, 101, 102],
       [102, 101, 101]])

In [146]:
arr4**2

array([[4, 4, 1],
       [1, 1, 4],
       [4, 1, 1]])

In [147]:
# Numpy - Broadcasting

In [149]:
arr = np.zeros((4,4))

In [150]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [151]:
row = np.array([1,2,3,4])

In [152]:
row

array([1, 2, 3, 4])

In [153]:
arr +row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [154]:
row.T

array([1, 2, 3, 4])

In [155]:
col = np.array([[1,2,3,4]])

In [156]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [157]:
col.T + arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [158]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [163]:
arr1=np.random.randint(1,4,(3,4))

In [164]:
arr1

array([[2, 1, 3, 1],
       [3, 1, 1, 3],
       [3, 2, 2, 1]])

In [165]:
np.sqrt(arr1)

array([[1.41421356, 1.        , 1.73205081, 1.        ],
       [1.73205081, 1.        , 1.        , 1.73205081],
       [1.73205081, 1.41421356, 1.41421356, 1.        ]])

In [167]:
np.exp(arr1)

array([[ 7.3890561 ,  2.71828183, 20.08553692,  2.71828183],
       [20.08553692,  2.71828183,  2.71828183, 20.08553692],
       [20.08553692,  7.3890561 ,  7.3890561 ,  2.71828183]])

In [168]:
np.log10(arr1)

array([[0.30103   , 0.        , 0.47712125, 0.        ],
       [0.47712125, 0.        , 0.        , 0.47712125],
       [0.47712125, 0.30103   , 0.30103   , 0.        ]])